#!/usr/bin/env python
# -*- coding: utf-8 -*-

import pandas as pd
from collections import OrderedDict
import spotlight
import re
import json, ast

Text = raw_input("Tweet : ")
annotations=spotlight.annotate('http://spotlight.sztaki.hu:2222/rest/annotate', Text)
                            
d = ast.literal_eval(json.dumps(annotations))

size = 2
h = filter(lambda person: person['types'] == 'DBpedia:Agent,Schema:Person,Http://xmlns.com/foaf/0.1/Person,DBpedia:Person' or person['types'] == 'DBpedia:Agent,Schema:Person,Http://xmlns.com/foaf/0.1/Person,DBpedia:Person,DBpedia:Politician' or person['types'] == 'DBpedia:Agent,Schema:Person,Http://xmlns.com/foaf/0.1/Person,DBpedia:Person,DBpedia:Politician,DBpedia:Senator' or person['types'] == 'DBpedia:Agent,Schema:Person,Http://xmlns.com/foaf/0.1/Person,DBpedia:Person,DBpedia:OfficeHolder' or person['types'] == 'DBpedia:Agent,Schema:Person,Http://xmlns.com/foaf/0.1/Person,DBpedia:Person,DBpedia:Politician,DBpedia:PrimeMinister', d)
m = []
for l in h:
    #print l['surfaceForm']
    #m = l['surfaceForm'] , l['URI']
    #print m
    m.append(l['surfaceForm']),m.append(l['URI'])
b = [m[i:i+size] for i  in range(0, len(m), size)]   

labels = ['Entity', 'URI']
print pd.DataFrame.from_records(b, columns=labels)   
